name: CI

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Install helm mirror
        run: |
          mkdir build
          cd build
          wget https://github.com/alekc-forks/helm-mirror/releases/download/v0.3.2/helm-mirror_0.3.2_linux_amd64.tar.gz
          tar xzvf helm-mirror_0.3.2_linux_amd64.tar.gz
          mv helm-mirror /usr/local/bin/
          cd ..
          rm -rf build
      - name: Sync repository
        run: |
          helm-mirror https://charts-backup.alekc.dev/ $(pwd)/docs/ -a
      - name: Commit and Push
        run: |
          git config --global user.email "syncbot@alekc.dev"
          git config --global user.name "Sync Bot"
          git add docs
          git update-index --refresh
          git diff-index --quiet HEAD || (git commit -a -m'[bot] update files' --allow-empty && git push)
